apiVersion: v1
kind: Namespace
metadata:
  name: game-20481
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-20481
  name: deployment-204890
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-204892
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-204892
    spec:
      containers:
      - image: arjit547/iaf
        imagePullPolicy: Always
        name: app-204892
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-20481
  name: service-204891
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-204892
---